# Generated by Django 2.1.1 on 2018-09-14 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_url', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='miniurl',
            name='username',
        ),
        migrations.AlterField(
            model_name='miniurl',
            name='LongURL',
            field=models.URLField(unique=True, verbose_name='Long URL'),
        ),
    ]
